### ISSUE TITLE
Version is not current.

### ISSUE THREAD

**Issue by rectagonal** [flathub/com.tic80.TIC_80#6]
Flathub states version is: 1.0.2164
But issuing "help version" from within TIC-80 states the version is 1.0.1 (b09c50c)
TIC welcome screen is also prompting that a newerer version is available.
I've checked several times and I can't fetch any newer package from flathub.

**Comment by kevinsmia1939** [comment]
hmm, that is strange, because this flatpak build and install the latest version 1.0.2164

**Comment by rectagonal** [comment]
"flatpak remote-info --log flathub com.tic80.TIC_80" outputs:
```
        ID: com.tic80.TIC_80
       Ref: app/com.tic80.TIC_80/x86_64/stable
      Arch: x86_64
    Branch: stable
Collection: org.flathub.Stable
  Download: 2.2 MB
 Installed: 5.3 MB
   Runtime: org.freedesktop.Platform/x86_64/22.08
       Sdk: org.freedesktop.Sdk/x86_64/22.08

    Commit: 87d3e5dcce626520eb7ddb53743cc65ac6ee1146e6739ae722068d795462a880
    Parent: 1a401a35f1f31d532c562f7a14f243b25e76644a9cbbbca9b797cbf8fe869c8a
   Subject: Upgrade runtime to 22.08 (27009b53)
      Date: 2022-12-23 22:02:07 +0000
   History: 

    Commit: 1a401a35f1f31d532c562f7a14f243b25e76644a9cbbbca9b797cbf8fe869c8a
   Subject: Upgrade runtime to 22.08 (27009b53)
      Date: 2022-12-23 22:02:07 +0000

    Commit: 15aa8cf87dde4ec196f00f6b5d05d55d031a5a64ee6e7c6ef42801166ce44068
   Subject: Enable network (fe5182ae)
      Date: 2022-06-20 20:12:20 +0000

    Commit: b02ede8b1ff5dd187235446ce459546018a0ac31fc2303afb5c286a0029ee33b
   Subject: remove pro version (b84c5e10)
      Date: 2022-06-17 09:48:52 +0000
```

I ran "flatpak update --commit=87d3e5dcce626520eb7ddb53743cc65ac6ee1146e6739ae722068d795462a880 com.tic80.TIC_80" to make sure im at the newest version.

It is still reporting as version 1.01 from within the app.
